platform :ios, '9.0'

target 'WayOfTea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WayOfTea
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

end
